src = [
  "app",
  "packages/smbmonitor/src",
]

exclude = [
  ".venv",
  "tests"
]

[lint]
select = [
  # use "ruff linter" to list all available linters
  "E",
  "W",
  "F",
  "I",
  "C",
  "B",
  "PL",
  "PT",
  "UP",
  "RUF",
  "N",
  "ASYNC",
  "C4",
  "EM",
  "FA",
  "ISC",
  "ICN",
  "RSE",
  "SLF",
  "SLOT",
  "SIM",
  "TID",
  "TCH",
  "PERF",
]
ignore = [
  "E501",    # line too long, handled by black
  "B008",    # do not perform function calls in argument defaults
  "C901",    # too complex
  "W191",    # indentation contains tabs
  "PLR0913", # too many arguments
  "PLR0912", # too many branches
  "EM101",   # exception must not use a string literal, assign to variable first
  "EM102",   # exception must not use an f-string literal, assign to variable first
  "PLR0915", # too many statements,
  "UP006",
  "UP035",
  "RUF023",
]

[lint.per-file-ignores]
"__init__.py" = [
  "F401",
]
"tests/*" = [
  "PLR2004",
  "PT011",
  "SLF001",
]

[format]
exclude = [
]

[lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true

[lint.flake8-pytest-style]
mark-parentheses = true
