---
services:
  ocrpdf:
    image: ghcr.io/ophiosdev/ocrpdf:latest
    container_name: ocrpdf
    environment:
      SMB_UNC_PATH: "${SMB_UNC_PATH}"
      SMB_USERNAME: "${SMB_USERNAME}"
      SMB_PASSWORD: "${SMB_PASSWORD}"
    volumes:
      - ocr_data:/data

volumes:
  ocr_data:
